name: labeler

on:
  pull_request:
    branches:
      - master
    types:
      - reopened
      - opened
      - synchronize

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler-content:
    name: Label for PR content
    if: github.repository == 'skyclouds2001/vite-react-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  labeler-size:
    name: Label for PR size
    if: github.repository == 'skyclouds2001/vite-react-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1.10.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_api_url: https://api.github.com
          xs_label: size/xs
          xs_max_size: 10
          s_label: size/s
          s_max_size: 100
          m_label: size/m
          m_max_size: 500
          l_label: size/l
          l_max_size: 1000
          xl_label: size/xl
          fail_if_xl: false
          message_if_xl: |
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          files_to_ignore: 'package-lock.json yarn.lock pnpm-lock.yaml'
  label-rebase-needed:
    name: Label for PR merge conflict
    if: github.repository == 'skyclouds2001/vite-react-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v3.0.3
        with:
          dirtyLabel: merge conflicts
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          commentOnDirty: |
            This pull request has conflicts, please resolve those before we can evaluate the pull request.
          commentOnClean: |
            Conflicts have been resolved. A maintainer will review the pull request shortly.
