name: new contributor

on:
  issues:
    types:
      - reopened
      - opened
  pull_request:
    types:
      - reopened
      - opened

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  new-contributor:
    name: Welcom new contributor
    if: github.repository == 'skyclouds2001/vite-react-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for your contribution ğŸ’ª

            As it's your first contribution be sure to check out the checklist.

            Welcome aboard â›µï¸!
          pr-message: |
            Hello! Thank you for your contribution ğŸ’ª

            As it's your first contribution be sure to check out the checklist.

            Welcome aboard â›µï¸!
