name: new contributor

on:
  - issues
  - pull_request

permissions:
  contents: none
  issues: none
  pull-requests: write

jobs:
  new-contributor:
    if: github.repository == 'skyclouds2001/vite-react-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for your contribution ğŸ’ª

            As it's your first contribution be sure to check out the checklist.

            Welcome aboard â›µï¸!
          pr-message: |
            Hello! Thank you for your contribution ğŸ’ª

            As it's your first contribution be sure to check out the checklist.

            Welcome aboard â›µï¸!
